
services:
  client:
    build: ./client
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE=http://server:5000
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
